version: 2.1
jobs:
  percy_snapshots:
    docker:
      - image: circleci/node:10-browsers

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: npm ci

      - run:
          name: Build
          command: npm run build

      - run:
          name: Percy snapshots
          command: npm run snapshots:ci

workflows:
  test:
    jobs:
      - percy_snapshots
